services:
  minecraft-rcon:
    container_name: minecraft-rcon
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
    
    restart: on-failure
    build: 
      context: build_container_rcon/
    tty: true
    tmpfs:
      - /run
      - /tmp
    logging: 
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

  minecraft-core:
    container_name: minecraft-core
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
      
    build: 
      context: build_container_core/
      args:
        - minecraft_server_jar_url=${minecraft_server_jar_url:-https://piston-data.mojang.com/v1/objects/45810d238246d90e811d896f87b14695b7fb6839/server.jar}
        - minecraft_server_version=${minecraft_server_version:-1.21.3}
    restart: on-failure
    ports:
      - 25565:25565
      - 25575:25575
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - type: volume
        source: minecraft-core
        target: /var/minecraft
    logging: 
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

  minecraft-database-admin:
    container_name: minecraft-database-admin
    image: phpmyadmin/phpmyadmin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-MYSQL_ROOT_PASSWORD_123}"
      PMA_HOST: "minecraft-database"
      PMA_ARBITRARY: 0
    restart: on-failure
    tty: true
    tmpfs:
      - /run
      - /tmp
    ports:
      - "30000-65530:80"
    logging: 
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

  minecraft-database:
    container_name: minecraft-database
    image: mysql
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-MYSQL_ROOT_PASSWORD_123}"
    restart: on-failure
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - type: volume
        source: minecraft-database
        target: /var/lib/mysql
    logging: 
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

volumes:
  minecraft-logs:
  minecraft-core:
  minecraft-database:
