services:
  minecraft-rcon:
    container_name: minecraft-rcon
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
    restart: on-failure
    build:
      context: build_container_rcon/
      args:
        - minecraft_server_config_rcon_host=${minecraft_server_config_rcon_host:-minecraft-core}
        - minecraft_server_config_rcon_port=${minecraft_server_config_rcon_port:-25575}
        - minecraft_server_config_rcon_password=${minecraft_server_config_rcon_password:-25575password@1}
    tty: true
    tmpfs:
      - /run
      - /tmp
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

  minecraft-core:
    container_name: minecraft-core
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
    build:
      context: build_container_core/
      args:
        - minecraft_server_jar_url=${minecraft_server_jar_url:-https://piston-data.mojang.com/v1/objects/45810d238246d90e811d896f87b14695b7fb6839/server.jar}
        - minecraft_server_version=${minecraft_server_version:-1.21.3}
        - minecraft_server_config_difficulty=${minecraft_server_config_difficulty:-normal}
        - minecraft_server_config_enable_command_block=${minecraft_server_config_enable_command_block:-false}
        - minecraft_server_config_enable_jmx_monitoring=${minecraft_server_config_enable_jmx_monitoring:-false}
        - minecraft_server_config_enable_query=${minecraft_server_config_enable_query:-false}
        - minecraft_server_config_enable_rcon=${minecraft_server_config_enable_rcon:-true}
        - minecraft_server_config_enable_status=${minecraft_server_config_enable_status:-true}
        - minecraft_server_config_enforce_secure_profile=${minecraft_server_config_enforce_secure_profile:-true}
        - minecraft_server_config_enforce_whitelist=${minecraft_server_config_enforce_whitelist:-false}
        - minecraft_server_config_entity_broadcast_range_percentage=${minecraft_server_config_entity_broadcast_range_percentage:-100}
        - minecraft_server_config_force_gamemode=${minecraft_server_config_force_gamemode:-false}
        - minecraft_server_config_function_permission_level=${minecraft_server_config_function_permission_level:-2}
        - minecraft_server_config_gamemode=${minecraft_server_config_gamemode:-survival}
        - minecraft_server_config_generate_structures=${minecraft_server_config_generate_structures:-true}
        - minecraft_server_config_generator_settings=${minecraft_server_config_generator_settings:-{}}
        - minecraft_server_config_hardcore=${minecraft_server_config_hardcore:-false}
        - minecraft_server_config_hide_online_players=${minecraft_server_config_hide_online_players:-false}
        - minecraft_server_config_initial_disabled_packs=${minecraft_server_config_initial_disabled_packs:-}
        - minecraft_server_config_initial_enabled_packs=${minecraft_server_config_initial_enabled_packs:-vanilla}
        - minecraft_server_config_level_name=${minecraft_server_config_level_name:-world}
        - minecraft_server_config_level_seed=${minecraft_server_config_level_seed:-}
        - minecraft_server_config_level_type=${minecraft_server_config_level_type:-minecraft\:normal}
        - minecraft_server_config_log_ips=${minecraft_server_config_log_ips:-true}
        - minecraft_server_config_max_chained_neighbor_updates=${minecraft_server_config_max_chained_neighbor_updates:-1000000}
        - minecraft_server_config_max_players=${minecraft_server_config_max_players:-10}
        - minecraft_server_config_max_tick_time=${minecraft_server_config_max_tick_time:-60000}
        - minecraft_server_config_max_world_size=${minecraft_server_config_max_world_size:-29999984}
        - minecraft_server_config_motd=${minecraft_server_config_motd:-Private server}
        - minecraft_server_config_network_compression_threshold=${minecraft_server_config_network_compression_threshold:-256}
        - minecraft_server_config_online_mode=${minecraft_server_config_online_mode:-true}
        - minecraft_server_config_op_permission_level=${minecraft_server_config_op_permission_level:-4}
        - minecraft_server_config_pause_when_empty_seconds=${minecraft_server_config_pause_when_empty_seconds:-60}
        - minecraft_server_config_player_idle_timeout=${minecraft_server_config_player_idle_timeout:-0}
        - minecraft_server_config_prevent_proxy_connections=${minecraft_server_config_prevent_proxy_connections:-false}
        - minecraft_server_config_pvp=${minecraft_server_config_pvp:-true}
        - minecraft_server_config_query_port=${minecraft_server_config_query_port:-25565}
        - minecraft_server_config_rate_limit=${minecraft_server_config_rate_limit:-0}
        - minecraft_server_config_rcon_password=${minecraft_server_config_rcon_password:-25575password@1}
        - minecraft_server_config_rcon_port=${minecraft_server_config_rcon_port:-25575}
        - minecraft_server_config_region_file_compression=${minecraft_server_config_region_file_compression:-deflate}
        - minecraft_server_config_require_resource_pack=${minecraft_server_config_require_resource_pack:-false}
        - minecraft_server_config_resource_pack=${minecraft_server_config_resource_pack:-}
        - minecraft_server_config_resource_pack_id=${minecraft_server_config_resource_pack_id:-}
        - minecraft_server_config_resource_pack_prompt=${minecraft_server_config_resource_pack_prompt:-}
        - minecraft_server_config_resource_pack_sha1=${minecraft_server_config_resource_pack_sha1:-}
        - minecraft_server_config_server_ip=${minecraft_server_config_server_ip:-}
        - minecraft_server_config_server_port=${minecraft_server_config_server_port:-25565}
        - minecraft_server_config_simulation_distance=${minecraft_server_config_simulation_distance:-10}
        - minecraft_server_config_spawn_monsters=${minecraft_server_config_spawn_monsters:-true}
        - minecraft_server_config_spawn_protection=${minecraft_server_config_spawn_protection:-16}
        - minecraft_server_config_sync_chunk_writes=${minecraft_server_config_sync_chunk_writes:-true}
        - minecraft_server_config_text_filtering_config=${minecraft_server_config_text_filtering_config:-}
        - minecraft_server_config_text_filtering_version=${minecraft_server_config_text_filtering_version:-0}
        - minecraft_server_config_use_native_transport=${minecraft_server_config_use_native_transport:-true}
        - minecraft_server_config_view_distance=${minecraft_server_config_view_distance:-10}
        - minecraft_server_config_white_list=${minecraft_server_config_white_list:-false}
    restart: on-failure
    ports:
      - 25565:25565
      - 25575:25575
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - type: volume
        source: minecraft-core
        target: /var/minecraft
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

  minecraft-database-admin:
    container_name: minecraft-database-admin
    image: phpmyadmin/phpmyadmin
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-MYSQL_ROOT_PASSWORD_123}"
      PMA_HOST: "minecraft-database"
      PMA_ARBITRARY: 0
    restart: on-failure
    tty: true
    tmpfs:
      - /run
      - /tmp
    ports:
      - "30000-65530:80"
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

  minecraft-database:
    container_name: minecraft-database
    image: mysql
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Tokyo
      LANG: "C"
      LANGUAGE: "C"
      LC_ALL: "C"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-MYSQL_ROOT_PASSWORD_123}"
    restart: on-failure
    tty: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - type: volume
        source: minecraft-database
        target: /var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "10"

volumes:
  minecraft-logs:
  minecraft-core:
  minecraft-database:
