apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: minecraft-core
  name: minecraft-core
spec:
  ports:
    - name: "25565"
      port: 25565
      targetPort: 25565
    - name: "19132"
      port: 19132
      protocol: UDP
      targetPort: 19132
    - name: "8123"
      port: 8123
      targetPort: 8123
    - name: "24454"
      port: 24454
      protocol: UDP
      targetPort: 24454
  selector:
    io.kompose.service: minecraft-core
