name: Docker Container for minecraft-server

on:
  push:
    paths:
      - "**"
  pull_request:
    paths:
      - "**"

permissions:
  contents: read

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "API access: https://github.com/n138-kz/isJP"
        run: curl https://api.n138.jp/isJP/ | jq

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Pull the image: phpmyadmin/phpmyadmin"
        run: docker pull phpmyadmin/phpmyadmin

      - name: "Pull the image: mysql"
        run: docker pull mysql

      - name: "Pull the image: almalinux:8"
        run: docker pull almalinux:8

      - name: "Pull the image: alpine"
        run: docker pull alpine

      - name: Build the Docker container
        run: docker compose build

      - name: Up check the Docker container
        run: docker compose up -d

      - name: Waiting for 30s
        run: sleep 30

      - name: "server.properties"
        run: docker compose exec -it minecraft-core cat server.properties

      - name: "mcrcon -t list"
        run: docker compose exec -it minecraft-rcon mcrcon list

      - name: Waiting for 30s
        run: sleep 30

      - name: "ls show the Docker containers"
        run: docker compose ls

      - name: "ps show the Docker containers"
        run: docker compose ps

      - name: "Log show the Docker container: minecraft-core"
        run: docker compose logs minecraft-core

      - name: "Log show the Docker container: minecraft-rcon"
        run: docker compose logs minecraft-rcon

      - name: "Log show the Docker container: minecraft-database"
        run: docker compose logs minecraft-database

      - name: "Log show the Docker container: minecraft-database-admin"
        run: docker compose logs minecraft-database-admin
