name: Docker Container for minecraft-server

on:
  push:
    paths:
      - "**"
  pull_request:
    paths:
      - "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Pull the image: phpmyadmin/phpmyadmin"
        run: docker pull phpmyadmin/phpmyadmin

      - name: "Pull the image: mysql"
        run: docker pull mysql

      - name: "Pull the image: almalinux:8"
        run: docker pull almalinux:8

      - name: "Pull the image: alpine"
        run: docker pull alpine

      - name: Build the Docker container
        run: docker compose build

      - name: Up check the Docker container
        run: docker compose up -d

      - name: Waiting for 30s
        run: sleep 30

      - name: "Log show the Docker container: minecraft-database"
        run: docker compose logs minecraft-core

      - name: "Log show the Docker container: minecraft-database"
        run: docker compose logs minecraft-rcon

      - name: "Log show the Docker container: minecraft-database"
        run: docker compose logs minecraft-database

      - name: "Log show the Docker container: minecraft-database"
        run: docker compose logs minecraft-database-admin
