name: Docker Container Build

on:
  workflow_dispatch:
  push:
    paths: 
      - '**/Dockerfile'
      - '**/compose.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create test .env
      run: touch .env

    - name: Build the Image
      working-directory: ./build_container_core_alpine
      run: docker build . --no-cache --tag dev
